---
name: "Test"
"on":
  push:
    branches-ignore:
      - 'dependabot/*'
  schedule:
    - cron: '22 22 * * 5'
env:
  IMAGE: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install bats
      run: sudo apt-get -y install bats > /dev/null

    - name: Run CI script
      run: ./tests/run.bats
